# Generated by Django 3.2.10 on 2021-12-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_log',
            name='humidity',
            field=models.FloatField(default=99),
            preserve_default=False,
        ),
    ]
